[package]
name = "web-bones-rs"
version = "0.1.0"
authors = ["Daniel Wilkins"]
license = "MIT OR Apache-2.0"

[dependencies]
rocket = { version = "0.3.14", features = ["tls"] }
rocket_codegen = "0.3.14"

#Internal Dependencies
route = { path = "route" }
