[package]
name = "guard"
version = "0.1.0"
authors = ["Daniel Wilkins <danielwilkins8@gmail.com>"]

[dependencies]
rocket = { version = "0.3.6", features = ["tls"] }

#Internal Dependencies
service = { path = "../service" }