[package]
name = "app"
version = "0.1.0"
authors = ["Daniel Wilkins <danielwilkins8@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
yew = "0.6"
transfer = { path = "../transfer"}
http = "0.1"
failure = "0.1"